#!/usr/bin/env python3
"""Generate the bilingual Lua v5 reference from a pinned CCB contract commit."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable

import jsonschema
import yaml


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config/lua-reference-v5.yml"
LANGUAGES = ("zh_CN", "en")
GENERATED_MARKER = (
    "<!-- GENERATED BY scripts/generate_lua_reference.py; DO NOT EDIT. -->"
)
HEX_COMMIT = re.compile(r"^[0-9a-f]{40}$")


class LuaReferenceError(ValueError):
    """The source contract or generated reference violates publication policy."""


def load_config(path: Path = CONFIG_PATH) -> dict[str, Any]:
    config = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(config, dict) or config.get("schema_version") != 1:
        raise LuaReferenceError("Lua reference config must use schema_version 1")
    if config.get("api_version") != 5:
        raise LuaReferenceError("Lua reference config must target API v5")
    if not HEX_COMMIT.fullmatch(str(config.get("source_commit", ""))):
        raise LuaReferenceError("Lua reference config needs a full source commit")
    sections = [page.get("section") for page in config.get("generated_pages", [])]
    expected = {
        "modules",
        "namespaces",
        "classes",
        "functions",
        "methods",
        "properties",
        "operators",
        "enums",
        "events",
        "hooks",
        "callbacks",
        "capabilities",
        "permissions",
        "manifest_fields",
    }
    if set(sections) != expected or len(sections) != len(expected):
        raise LuaReferenceError("generated_pages must contain each Lua v5 section once")
    return config


def git_show(repository: Path, commit: str, source_path: str) -> bytes:
    result = subprocess.run(
        ["git", "-C", str(repository), "show", f"{commit}:{source_path}"],
        check=False,
        capture_output=True,
    )
    if result.returncode != 0:
        detail = result.stderr.decode("utf-8", errors="replace").strip()
        raise LuaReferenceError(
            f"cannot read {source_path} at {commit}: {detail or 'git show failed'}"
        )
    return result.stdout


def source_json(repository: Path, commit: str, path: str) -> dict[str, Any]:
    try:
        value = json.loads(git_show(repository, commit, path))
    except json.JSONDecodeError as error:
        raise LuaReferenceError(f"invalid JSON in {path}: {error}") from error
    if not isinstance(value, dict):
        raise LuaReferenceError(f"{path} must contain a JSON object")
    return value


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def documentation_records(value: Any) -> Iterable[dict[str, str]]:
    if isinstance(value, dict):
        documentation = value.get("documentation")
        if isinstance(documentation, dict):
            yield documentation
        for key, child in value.items():
            if key != "documentation":
                yield from documentation_records(child)
    elif isinstance(value, list):
        for child in value:
            yield from documentation_records(child)


def anchor_for(documentation_id: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", documentation_id.lower()).strip("-")
    digest = hashlib.sha256(documentation_id.encode("utf-8")).hexdigest()[:12]
    return f"symbol-{slug}-{digest}"


def validate_contract(
    contract: dict[str, Any],
    contract_schema: dict[str, Any],
    coverage: dict[str, Any],
    coverage_schema: dict[str, Any],
) -> dict[str, str]:
    jsonschema.Draft202012Validator.check_schema(contract_schema)
    jsonschema.Draft202012Validator(contract_schema).validate(contract)
    jsonschema.Draft202012Validator.check_schema(coverage_schema)
    jsonschema.Draft202012Validator(coverage_schema).validate(coverage)
    if contract.get("api_version") != 5 or coverage.get("api_version") != 5:
        raise LuaReferenceError("contract and coverage must target API v5")

    direct_sections = (
        "modules",
        "namespaces",
        "classes",
        "functions",
        "methods",
        "properties",
        "operators",
        "enums",
        "events",
        "hooks",
        "callbacks",
        "capabilities",
        "manifest_fields",
    )
    actual_counts = {name: len(contract[name]) for name in direct_sections}
    actual_counts["class_fields"] = sum(
        len(entry.get("fields", [])) for entry in contract["classes"]
    )
    actual_counts["event_fields"] = sum(
        len(entry.get("fields", [])) for entry in contract["events"]
    )
    if coverage.get("sections") != actual_counts:
        raise LuaReferenceError("coverage section counts do not match the contract")

    occurrences: dict[str, set[str]] = {}
    for section in direct_sections:
        for record in documentation_records(contract[section]):
            identity = record.get("id")
            if not isinstance(identity, str) or not identity:
                raise LuaReferenceError(f"{section} contains documentation without an id")
            if record.get("status") != "generated-contract-source":
                raise LuaReferenceError(f"{identity} has an unexpected documentation status")
            occurrences.setdefault(identity, set()).add(section)

    top_level_properties = {
        item["documentation"]["id"] for item in contract["properties"]
    }
    repeated = {
        identity: sections
        for identity, sections in occurrences.items()
        if len(sections) > 1
    }
    if set(repeated) != top_level_properties or any(
        sections != {"classes", "properties"} for sections in repeated.values()
    ):
        raise LuaReferenceError(
            "only native properties may repeat between class fields and properties"
        )
    documentation = {
        identity: ("properties" if identity in top_level_properties else next(iter(sections)))
        for identity, sections in occurrences.items()
    }

    undocumented = coverage.get("undocumented_symbols", {})
    if undocumented.get("count") != 0 or undocumented.get("ids") != []:
        raise LuaReferenceError("public Lua contract still has undocumented symbols")
    public_symbols = coverage.get("public_symbols")
    if (
        public_symbols != len(documentation)
        or coverage.get("documented_symbols") != len(documentation)
        or coverage.get("inventory_coverage_percent") != 100.0
    ):
        raise LuaReferenceError("Lua public denominator is not covered at 100%")

    anchors = [anchor_for(identity) for identity in documentation]
    if len(anchors) != len(set(anchors)):
        raise LuaReferenceError("public documentation ids produce duplicate anchors")
    return documentation


def validate_example(
    config: dict[str, Any],
    source_files: dict[str, bytes],
    manifest_schema: dict[str, Any],
    contract: dict[str, Any],
    require_luac: bool,
) -> None:
    root = config["example_root"].rstrip("/") + "/"

    def parsed(relative: str) -> Any:
        try:
            return json.loads(source_files[root + relative])
        except json.JSONDecodeError as error:
            raise LuaReferenceError(f"invalid example JSON: {relative}: {error}") from error

    manifest = parsed("lua/manifest.json")
    modinfo = parsed("modinfo.json")
    if not isinstance(manifest, dict):
        raise LuaReferenceError("example Lua manifest must contain an object")
    jsonschema.Draft202012Validator.check_schema(manifest_schema)
    jsonschema.Draft202012Validator(manifest_schema).validate(manifest)
    if (
        not isinstance(modinfo, list)
        or len(modinfo) != 1
        or not isinstance(modinfo[0], dict)
        or modinfo[0].get("type") != "MOD_INFO"
    ):
        raise LuaReferenceError("example modinfo must contain exactly one MOD_INFO")
    if modinfo[0].get("id") != manifest.get("id"):
        raise LuaReferenceError("example Mod id and Lua manifest id differ")
    if modinfo[0].get("version") != manifest.get("version"):
        raise LuaReferenceError("example Mod and Lua manifest versions differ")

    callables = {
        item["id"]: item
        for section in ("functions", "methods")
        for item in contract[section]
    }
    requested = set(config["example_contract_symbols"])
    missing = sorted(requested - set(callables))
    if missing:
        raise LuaReferenceError(f"example uses missing contract symbols: {missing}")
    capabilities = set(manifest["capabilities"])
    missing_capabilities = {
        identity: sorted(set(callables[identity].get("capabilities", [])) - capabilities)
        for identity in sorted(requested)
        if set(callables[identity].get("capabilities", [])) - capabilities
    }
    if missing_capabilities:
        raise LuaReferenceError(
            f"example manifest lacks required capabilities: {missing_capabilities}"
        )

    executable = shutil.which("luac")
    if executable is None:
        if require_luac:
            raise LuaReferenceError("luac is required for the complete example")
        return
    with tempfile.TemporaryDirectory() as directory:
        for relative in ("lua/main.lua", "lua/lib/model.lua"):
            target = Path(directory) / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(source_files[root + relative])
            result = subprocess.run(
                [executable, "-p", str(target)],
                check=False,
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                raise LuaReferenceError(
                    f"example Lua syntax failed for {relative}: "
                    f"{(result.stderr or result.stdout).strip()}"
                )


def json_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def source_url(config: dict[str, Any], source: dict[str, Any]) -> str:
    base = config["source_repository"].rstrip("/")
    commit = config["source_commit"]
    line = source.get("line")
    suffix = f"#L{line}" if isinstance(line, int) else ""
    return f"{base}/blob/{commit}/{source['path']}{suffix}"


def render_sources(
    config: dict[str, Any], sources: list[dict[str, Any]], language: str
) -> list[str]:
    label = "来源" if language == "zh_CN" else "Sources"
    if not sources:
        return [f"**{label}:** none", ""]
    lines = [f"**{label}:**", ""]
    for source in sources:
        location = source["path"]
        if isinstance(source.get("line"), int):
            location += f":{source['line']}"
        authority = source.get("authority", "contract")
        lines.append(
            f"- [`{location}`]({source_url(config, source)}) — {authority}"
        )
    lines.append("")
    return lines


def documented_heading(item: dict[str, Any], level: int) -> str:
    documentation = item.get("documentation")
    if documentation and "id" in documentation:
        identity = str(item.get("id") or item.get("name") or documentation["id"])
        return (
            f"{'#' * level} `{identity}` "
            f"{{ #{anchor_for(documentation['id'])} }}"
        )
    identity = str(item.get("id") or item.get("name") or "item")
    return f"{'#' * level} `{identity}`"


def render_documented_item(
    config: dict[str, Any],
    item: dict[str, Any],
    language: str,
    level: int = 2,
    excluded: set[str] | None = None,
    section: str = "",
) -> list[str]:
    lines = [documented_heading(item, level), ""]
    is_zh = language == "zh_CN"

    # 1. Render Lua Signature Block
    sig_lines = []
    name = item.get("name") or item.get("id") or ""
    cls = item.get("class", "")
    ns = item.get("namespace", "")
    params = item.get("parameters", [])
    returns = item.get("returns", [])
    style = item.get("style", "")
    fields = item.get("fields", [])
    members = item.get("members", [])
    values = item.get("values", []) or members
    payload = item.get("payload", [])

    if section == "functions" or style == "function":
        full_fn = f"{ns}.{name}" if ns else name
        param_sigs = [f"{p['name']}: {p.get('declaration', 'any')}{'?' if p.get('optional') else ''}" for p in params]
        ret_sig = f" -> {', '.join(r.get('declaration', 'void') for r in returns)}" if returns else ""
        sig_lines = [
            "```lua",
            f"function {full_fn}({', '.join(param_sigs)}){ret_sig}",
            "```",
            "",
        ]
    elif section == "methods" or style == "method":
        param_sigs = [f"{p['name']}: {p.get('declaration', 'any')}{'?' if p.get('optional') else ''}" for p in params]
        ret_sig = f" -> {', '.join(r.get('declaration', 'void') for r in returns)}" if returns else ""
        sep = ":" if style == "method" else "."
        sig_lines = [
            "```lua",
            f"function {cls}{sep}{name}({', '.join(param_sigs)}){ret_sig}",
            "```",
            "",
        ]
    elif section == "classes" or "fields" in item:
        decl = item.get("declaration", name)
        sig_lines = [
            "```lua",
            f"---@class {decl}",
            f"local {name} = {{}}",
            "```",
            "",
        ]
    elif section == "events":
        sig_lines = [
            "```lua",
            f'-- {"订阅事件" if is_zh else "Subscribe to event"}',
            f'events.on("{name}", function(event)',
            f'    -- {"处理事件逻辑" if is_zh else "Handle event logic"}',
            "end)",
            "```",
            "",
        ]
    elif section == "hooks":
        payload_list = payload if isinstance(payload, list) else []
        payload_sigs = [f"{p['name']}: {p.get('declaration', 'any')}" for p in payload_list if isinstance(p, dict) and 'name' in p]
        payload_args = [p.get('name', 'arg') for p in payload_list if isinstance(p, dict)]
        ret_sig = f" -> {', '.join(r.get('declaration', 'void') for r in returns)}" if isinstance(returns, list) and returns else ""
        sig_lines = [
            "```lua",
            f'-- {"注册拦截 Hook" if is_zh else "Register hook interceptor"}',
            f'game.hooks.on("{name}", function({", ".join(payload_args)}){ret_sig}',
            f'    -- {"同步拦截并返回值" if is_zh else "Intercept and return result"}',
            "end)",
            "```",
            "",
        ]
    elif section == "callbacks":
        sig_lines = [
            "```lua",
            f'-- Callback: {name}',
            f'-- Kind: {item.get("kind", "callback")} (Payload: {item.get("payload_type", "table")} -> Result: {item.get("result_type", "void")})',
            "```",
            "",
        ]
    elif section == "enums":
        sig_lines = [
            "```lua",
            f"---@enum {name}",
            "```",
            "",
        ]
    elif section == "namespaces":
        sig_lines = [
            "```lua",
            f"-- Namespace: {name}",
            f"local {name.split('.')[-1]} = {name}",
            "```",
            "",
        ]
    elif section == "properties" or "read_only" in item:
        ro_tag = " (readonly)" if item.get("read_only") else ""
        decl = item.get("declaration", "any")
        full_prop = f"{cls}.{name}" if cls else name
        sig_lines = [
            "```lua",
            f"---@field {name} {decl}{ro_tag}",
            f"{full_prop} = ... -- {decl}",
            "```",
            "",
        ]
    elif section == "capabilities":
        sig_lines = [
            "```lua",
            f'-- Capability: "{name}"',
            f'-- Minimum API: CCB Lua 0.1',
            "```",
            "",
        ]
    elif section == "manifest_fields":
        req = "required" if item.get("required") else "optional"
        sig_lines = [
            "```json",
            f'"{name}": ... // {req}',
            "```",
            "",
        ]
    elif section == "modules":
        sig_lines = [
            "```lua",
            f'-- Module: {name} (Mode: {item.get("mode", "lua")})',
            "```",
            "",
        ]
    elif section == "operators":
        sig_lines = [
            "```lua",
            f'-- Operator: {item.get("name", "op")} for {cls}',
            "```",
            "",
        ]

    lines.extend(sig_lines)

    # 2. Render Parameters Table
    if params:
        lines.append(f"**{'参数列表 (Parameters)' if is_zh else 'Parameters'}:**")
        lines.append("")
        lines.append(f"| {'参数名' if is_zh else 'Parameter'} | {'类型' if is_zh else 'Type'} | {'要求' if is_zh else 'Requirement'} |")
        lines.append("| :--- | :--- | :--- |")
        for p in params:
            req = ("可选 (Optional)" if p.get("optional") else "必选 (Required)") if is_zh else ("Optional" if p.get("optional") else "Required")
            lines.append(f"| `{p.get('name', 'arg')}` | `{p.get('declaration', 'any')}` | {req} |")
        lines.append("")

    # 3. Render Return Value
    if returns and isinstance(returns, list):
        lines.append(f"**{'返回值 (Returns)' if is_zh else 'Returns'}:**")
        lines.append("")
        for r in returns:
            if isinstance(r, dict):
                lines.append(f"- `{r.get('declaration', 'void')}`")
            else:
                lines.append(f"- `{r}`")
        lines.append("")

    # 4. Render Fields (for classes and events)
    if fields and isinstance(fields, list):
        lines.append(f"**{'字段属性 (Fields)' if is_zh else 'Fields'}:**")
        lines.append("")
        lines.append(f"| {'字段名' if is_zh else 'Field'} | {'类型' if is_zh else 'Type'} | {'特性' if is_zh else 'Access'} |")
        lines.append("| :--- | :--- | :--- |")
        for f in fields:
            access = ("只读" if f.get("read_only") else "可读写") if is_zh else ("Read-only" if f.get("read_only") else "Read-write")
            lines.append(f"| `{f.get('name', 'field')}` | `{f.get('declaration', 'any')}` | {access} |")
        lines.append("")

    # 5. Render Enum Values
    if values and isinstance(values, list):
        lines.append(f"**{'枚举值列表 (Values)' if is_zh else 'Enum Values'}:**")
        lines.append("")
        for v in values:
            lines.append(f"- `{v}`")
        lines.append("")

    # 6. Capabilities & Permissions Badge
    caps = item.get("capabilities", [])
    if caps and isinstance(caps, list):
        caps_str = ", ".join(f"`{c}`" for c in caps)
        lines.append(f"🛡️ **{'所需权限 (Required Capabilities)' if is_zh else 'Required Capabilities'}:** {caps_str}")
        lines.append("")

    # 7. Error Handling Mode
    errors = item.get("errors")
    if isinstance(errors, dict) and errors.get("conditions"):
        conds = "; ".join(errors.get("conditions", []))
        mode = errors.get("mode", "lua-error")
        lines.append(f"⚠️ **{'错误模式' if is_zh else 'Error Handling'}:** `{mode}` ({conds})")
        lines.append("")

    # 8. Sources
    lines.extend(render_sources(config, item.get("sources", []), language))
    return lines


def render_section(
    config: dict[str, Any],
    page: dict[str, Any],
    contract: dict[str, Any],
    language: str,
) -> str:
    section = page["section"]
    title = page[f"{language}_title"]
    count = len(contract[section]) if section != "permissions" else 1
    is_zh = language == "zh_CN"
    if is_zh:
        intro = (
            f"本页为 CCB Lua 0.1 平台自动生成的 `{title}` 规范手册，"
            f"收录 {count} 条 `{section}` 契约记录。"
        )
    else:
        intro = (
            f"This page is the automatically generated reference manual for CCB Lua 0.1, "
            f"containing {count} `{section}` contract records."
        )
    lines = [GENERATED_MARKER, "", f"# {title}", "", intro, ""]
    if section == "permissions":
        permission = contract["permissions"]
        lines.append("## 权限系统模型" if is_zh else "## Permission System Model")
        lines.append("")
        lines.append(f"- **模型类型 (Model):** `{permission.get('model', 'standard')}`")
        lines.append(f"- **Manifest 声明字段 (Manifest Field):** `{permission.get('manifest_field', 'capabilities')}`")
        lines.append("")
        lines.extend(render_sources(config, permission.get("sources", []), language))
    else:
        for item in contract[section]:
            nested = {"fields"} if section in {"classes", "events"} else set()
            lines.extend(
                render_documented_item(
                    config,
                    item,
                    language,
                    excluded=nested,
                    section=section,
                )
            )
            for field in item.get("fields", []):
                lines.extend(render_documented_item(config, field, language, level=3, section="properties"))
    return "\n".join(lines).rstrip() + "\n"


def fenced(language: str, content: str) -> list[str]:
    return [f"```{language}", content.rstrip(), "```", ""]


def render_example(
    config: dict[str, Any], source_files: dict[str, bytes], language: str
) -> str:
    page = config["example_page"]
    title = page[f"{language}_title"]
    root = config["example_root"].rstrip("/") + "/"
    if language == "zh_CN":
        intro = (
            "这是主仓库中可加载示例 Mod 的完整镜像。复制整个目录，不能只复制 "
            "`main.lua`；Manifest、Mod id、依赖与 capability 共同构成加载契约。"
        )
        validation = (
            "生成器已用 Manifest Schema 校验 JSON、核对 Mod/Manifest id 与版本、"
            "核对 23 个公开 API 调用的 capability，并使用可用的 `luac -p` 检查 Lua。"
        )
        source_label = "固定来源"
    else:
        intro = (
            "This is the complete mirror of the loadable example Mod in the source "
            "repository. Copy the whole directory, not only `main.lua`: its manifest, "
            "Mod id, dependencies, and capabilities form one loading contract."
        )
        validation = (
            "The generator validates JSON against the Manifest Schema, matches the Mod "
            "and manifest ids and versions, checks capabilities for 23 public API calls, "
            "and runs `luac -p` when the compiler is available."
        )
        source_label = "Pinned source"
    lines = [GENERATED_MARKER, "", f"# {title}", "", intro, "", validation, ""]
    lines.extend(
        [
            f"**{source_label}:** "
            f"[`{config['example_root']}`]("
            f"{config['source_repository']}/tree/{config['source_commit']}/"
            f"{config['example_root']})",
            "",
            "## File tree" if language == "en" else "## 文件树",
            "",
            "```text",
            "api_v5_mod/",
            "├── README.md",
            "├── modinfo.json",
            "└── lua/",
            "    ├── manifest.json",
            "    ├── main.lua",
            "    └── lib/model.lua",
            "```",
            "",
        ]
    )
    language_for = {
        "README.md": "markdown",
        "modinfo.json": "json",
        "lua/manifest.json": "json",
        "lua/main.lua": "lua",
        "lua/lib/model.lua": "lua",
    }
    for relative in config["example_files"]:
        lines.extend([f"## `{relative}`", ""])
        content = source_files[root + relative].decode("utf-8")
        lines.extend(fenced(language_for[relative], content))
    return "\n".join(lines).rstrip() + "\n"


def strip_front_matter(content: str) -> tuple[str, str]:
    if not content.startswith("---\n"):
        return "", content.lstrip("\n")
    end = content.find("\n---\n", 4)
    if end < 0:
        raise LuaReferenceError("generated page has unterminated front matter")
    boundary = end + len("\n---\n")
    return content[:boundary] + "\n", content[boundary:].lstrip("\n")


def page_path(language: str, path: str) -> Path:
    return ROOT / "docs" / language / path


def expected_page_outputs(
    config: dict[str, Any], contract: dict[str, Any], source_files: dict[str, bytes]
) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for page in config["generated_pages"]:
        for language in LANGUAGES:
            outputs[page_path(language, page["path"])] = render_section(
                config, page, contract, language
            )
    example = config["example_page"]
    for language in LANGUAGES:
        outputs[page_path(language, example["path"])] = render_example(
            config, source_files, language
        )
    return outputs


def publication_report(
    config: dict[str, Any],
    contract_bytes: bytes,
    coverage: dict[str, Any],
    documentation: dict[str, str],
) -> dict[str, Any]:
    page_by_section = {
        page["section"]: page for page in config["generated_pages"]
    }
    symbols = []
    for identity, section in sorted(documentation.items()):
        page = page_by_section[section]
        symbols.append(
            {
                "documentation_id": identity,
                "section": section,
                "page_id": page["id"],
                "anchor": anchor_for(identity),
                "paths": {
                    language: f"docs/{language}/{page['path']}"
                    for language in LANGUAGES
                },
            }
        )
    public_symbols = coverage["public_symbols"]
    return {
        "schema_version": 1,
        "api_version": 5,
        "generated_by": "python3 scripts/generate_lua_reference.py",
        "source_repository": config["source_repository"],
        "source_commit": config["source_commit"],
        "pending_source_pr": config["pending_source_pr"],
        "contract_sha256": sha256_bytes(contract_bytes),
        "contract_public_symbols": public_symbols,
        "contract_documented_symbols": coverage["documented_symbols"],
        "contract_undocumented_symbols": coverage["undocumented_symbols"],
        "inventory_coverage_percent": coverage["inventory_coverage_percent"],
        "generated_reference_symbols": len(symbols),
        "generated_reference_coverage_percent": round(
            100.0 * len(symbols) / public_symbols, 2
        ),
        "production_published_coverage_percent": 0.0,
        "publication_status": "draft-pending-source-pr",
        "sections": coverage["sections"],
        "generated_reference_pages": len(config["generated_pages"]) + 1,
        "generated_bilingual_pages": 2 * (len(config["generated_pages"]) + 1),
        "symbols": symbols,
    }


def write_or_check(outputs: dict[Path, str], check: bool) -> list[Path]:
    stale: list[Path] = []
    for path, expected_body in outputs.items():
        if path.exists():
            content = path.read_text(encoding="utf-8")
            front_matter, actual_body = strip_front_matter(content)
        else:
            front_matter, actual_body = "", ""
        if actual_body == expected_body:
            continue
        stale.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(front_matter + expected_body, encoding="utf-8")
    return stale


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-repo",
        type=Path,
        default=os.environ.get("CCB_SOURCE_REPO"),
        help="CCB Git checkout containing the pinned source commit",
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--require-luac", action="store_true")
    return parser.parse_args()


def main() -> int:
    arguments = parse_args()
    if arguments.source_repo is None:
        print("--source-repo or CCB_SOURCE_REPO is required", file=sys.stderr)
        return 2
    try:
        config = load_config()
        repository = arguments.source_repo.resolve()
        commit = config["source_commit"]
        contract_bytes = git_show(repository, commit, config["contract_path"])
        contract = json.loads(contract_bytes)
        contract_schema = source_json(repository, commit, config["contract_schema_path"])
        coverage = source_json(repository, commit, config["coverage_path"])
        coverage_schema = source_json(repository, commit, config["coverage_schema_path"])
        manifest_schema = source_json(repository, commit, config["manifest_schema_path"])
        documentation = validate_contract(
            contract, contract_schema, coverage, coverage_schema
        )
        source_files = {
            f"{config['example_root'].rstrip('/')}/{relative}": git_show(
                repository,
                commit,
                f"{config['example_root'].rstrip('/')}/{relative}",
            )
            for relative in config["example_files"]
        }
        validate_example(
            config,
            source_files,
            manifest_schema,
            contract,
            arguments.require_luac,
        )
        outputs = expected_page_outputs(config, contract, source_files)
        report = publication_report(
            config, contract_bytes, coverage, documentation
        )
        report_schema = json.loads(
            (ROOT / "schemas/lua-v5-reference-coverage.schema.json").read_text(
                encoding="utf-8"
            )
        )
        jsonschema.Draft202012Validator.check_schema(report_schema)
        jsonschema.Draft202012Validator(
            report_schema, format_checker=jsonschema.FormatChecker()
        ).validate(report)
        report_path = ROOT / config["report_path"]
        outputs[report_path] = json.dumps(
            report, ensure_ascii=False, indent=2, sort_keys=True
        ) + "\n"
        stale = write_or_check(outputs, arguments.check)
    except (
        OSError,
        KeyError,
        TypeError,
        json.JSONDecodeError,
        jsonschema.ValidationError,
        jsonschema.SchemaError,
        LuaReferenceError,
    ) as error:
        print(error, file=sys.stderr)
        return 1

    if arguments.check and stale:
        for path in stale:
            print(f"stale Lua reference output: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    action = "checked" if arguments.check else "generated"
    print(
        f"{action} {len(outputs) - 1} bilingual Lua reference pages and one report; "
        f"{len(documentation)} public symbols covered"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
